spring.application.name=ecommerce

spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce

spring.datasource.username=postgres

spring.datasource.password=postgres

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.flyway.enabled=true

spring.jpa.defer-datasource-initialization=false

# Fragella API
fragella.api.base-url=https://api.fragella.com/api/v1
fragella.api.key=${FRAGELLA_API_KEY}
stripe.webhook-secret=${STRIPE_WEBHOOK_SECRET}